In [5]:
import numpy 
import scipy
from scipy import ndimage


im = numpy.matrix([[2,2,2], [2,2,2], [6,6,6]])
dx = ndimage.sobel(im, 0)  # horizontal derivative
dy = ndimage.sobel(im, 1)  # vertical derivative
mag = numpy.hypot(dx, dy)  # magnitude
mag *= 255.0 / numpy.max(mag)  # normalize (Q&D)

print('Sx:',dx)
print('Sy:',dy)



Sx: [[ 0  0  0]
 [16 16 16]
 [16 16 16]]
Sy: [[0 0 0]
 [0 0 0]
 [0 0 0]]
